---
- name: Copy jar file to inventory i.e. Pull docker image
  hosts: all
  tasks:
          - name: Pull junit devops image 
            docker_image:
                  name: jaggu21/scientific_calculator 
                  source: pull
