- name: pull mini_project image
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: stopping old container
      shell: docker ps -aq --filter=status=running | xargs -r docker stop

    - name: deleting old container
      shell: docker ps -aq --filter=status=exited | xargs -r docker rm

    - name: remove old image
      shell: docker images -q --filter=reference="jaggu21/scientific_calculator" | xargs -r docker rmi -f

    - name: pull docker image
      shell: docker pull jaggu21/scientific_calculator

    - name: creating updated container
      shell: docker run -id jaggu21/scientific_calculator
